# Looker API credentials
base_url: https://looker.mediamarktsaturn.com
client_id: CwHdnY2Dzbphn9jYDdGG
client_secret: nNyd54pqcG2NWHJcG35Ptmm5
project: kvb_reporting

# Timeout settings for large projects
timeout: 1200  # 20 minutes

# Optional settings
# api_version: 4.0  # Always use 4.0 with your SDK version
# port: 443  # Usually not needed for cloud instances
# log_dir: logs  # Directory for log files

# SQL validator settings
# concurrency: 10  # Number of concurrent queries
# chunk_size: 500  # Maximum dimensions per query

# LookML validator settings
# severity: warning  # Severity threshold (info, warning, error)

# Content validator settings
# exclude_personal: true  # Exclude content in personal folders

# Optional global settings
log_dir: logs

# SQL validator settings
concurrency: 10
incremental: true

# Content validator settings
exclude_personal: true
content_incremental: true

# LookML validator settings
severity: warning